name: surge deploy

on: push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'maxgames.surge.sh'
          project: '.'
          login: maxwick456@gmail.com
          token: bbacdc6f-6cbd-41d0-ada0-fae68357dc07
